export const carData = [
    {
      id: 1,
      title: "Model S",
      price: 79999,
      company: "Tesla",
      info: "Electric sedan with long range and premium features.",
      inCart: false,
      count: 0,
    },
    {
      id: 2,
      title: "Mustang GT",
      price: 55999,
      company: "Ford",
      info: "Iconic muscle car with powerful V8 engine.",
      inCart: false,
      count: 0,
    },
    {
      id: 3,
      title: "Civic Type R",
      price: 42999,
      company: "Honda",
      info: "Performance hatchback with aggressive styling and turbocharged engine.",
      inCart: false,
      count: 0,
    },
    {
      id: 4,
      title: "Camry XSE",
      price: 35999,
      company: "Toyota",
      info: "Mid-size sedan known for reliability and comfort.",
      inCart: false,
      count: 0,
    },
    {
      id: 5,
      title: "A4",
      price: 44999,
      company: "Audi",
      info: "Luxury compact sedan with premium interior and technology.",
      inCart: false,
      count: 0,
    },
    {
      id: 6,
      title: "3 Series",
      price: 46999,
      company: "BMW",
      info: "Sporty and refined compact executive car.",
      inCart: false,
      count: 0,
    },
    {
      id: 7,
      title: "Charger SRT",
      price: 72999,
      company: "Dodge",
      info: "High-performance full-size sedan with bold styling.",
      inCart: false,
      count: 0,
    },
    {
      id: 8,
      title: "Altima SR",
      price: 31999,
      company: "Nissan",
      info: "Sleek and efficient sedan with modern features.",
      inCart: false,
      count: 0,
    }
  ];
  